apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apis4harnessingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  namespace: apis4harness      
spec:
  rules:
  - host:
    http:
      paths:
      - path: /apis4harness
        backend:
          serviceName: apis4harnessservice
          servicePort: http