---
apiVersion: v1
kind: Service
metadata:
  name: apis4harnessservice
  namespace: apis4harness
spec:
  ports:
  - name: http
    targetPort: 3000
    port: 3000
  selector:
    app: apis4harness
    microservice: app